# Generated by Django 2.1.7 on 2019-05-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=100, verbose_name='Pracownik')),
                ('position', models.CharField(max_length=100, verbose_name='Stanowisko')),
                ('site', models.CharField(max_length=100, verbose_name='Budowa')),
                ('date', models.DateField(verbose_name='Data')),
                ('cash', models.DecimalField(decimal_places=0, default=0, max_digits=3, verbose_name='Dniówka')),
            ],
        ),
    ]
